Dia = input('Qual seu dia de nascimento?')
Mes = input('Qual seu mes de nascimento?')
Ano = input('Qual seu ano de nascimento?')
print('Você nasceu no dia', Dia, 'de', Mes, 'de', Ano, '. Correto?')
print('então você tem', int(2022) - int(Ano), 'anos')
